services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-kasir_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    container_name: db_migrate
    networks:
      - app-network
    volumes:
      - ./etc/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-mypassword}@postgres:5432/${POSTGRES_DB:-kasir_db}?sslmode=disable",
        "up",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-play-app:latest
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      DB_NAME: ${POSTGRES_DB:-kasir_db}
      DB_SSL_MODE: disable
      REDIS_ADDR: redis:6379
      # Standard OpenTelemetry Environment Variables
      OTEL_SERVICE_NAME: "kasir-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otelcol:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.91.0
    volumes:
      - ./otelcol/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC (dari app)
      - "8889:8889" # Prometheus Exporter (dibaca Prometheus)
    restart: always
    command: ["--config=/etc/otelcol/config.yaml"]
    networks:
      - app-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - otelcol
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
