ALTER TABLE categories
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN updated_at TYPE TIMESTAMP,
  ALTER COLUMN deleted_at TYPE TIMESTAMP;

ALTER TABLE products
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN updated_at TYPE TIMESTAMP,
  ALTER COLUMN deleted_at TYPE TIMESTAMP;

ALTER TABLE transactions
  ALTER COLUMN created_at TYPE TIMESTAMP;

ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN updated_at TYPE TIMESTAMP;
